// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Gravion.Noesis.Infrastructure.Data;

namespace Gravion.Noesis.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250101000000_AddImportJobState")]
    partial class AddImportJobState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasPostgresExtension("vector");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Chunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasColumnType("text");

                    b.Property<int>("ChunkIndex")
                        .HasColumnName("chunk_index")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocId")
                        .HasColumnName("doc_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Heading")
                        .HasColumnName("heading")
                        .HasColumnType("text");

                    b.Property<string>("HeadingPath")
                        .HasColumnName("heading_path")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnName("source_id")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenCount")
                        .HasColumnName("token_count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("DocId");

                    b.ToTable("chunks");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Doc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasColumnName("content_hash")
                        .HasColumnType("text");

                    b.Property<string>("ContentMd")
                        .HasColumnName("content_md")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnName("indexed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnName("source_id")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SourceId", "Url" }, "IX_docs_source_id_url")
                        .IsUnique();

                    b.HasIndex("SourceId");

                    b.ToTable("docs");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Embedding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChunkId")
                        .HasColumnName("chunk_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dimensions")
                        .HasColumnName("dimensions")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnName("model")
                        .HasColumnType("text");

                    b.Property<float[]>("Vector")
                        .HasColumnName("vector")
                        .HasColumnType("vector");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChunkId", "Model" }, "IX_embeddings_chunk_id_model")
                        .IsUnique();

                    b.HasIndex("ChunkId");

                    b.ToTable("embeddings");
                });

            modelBuilder.Entity("Gravion.Noesis.UseCases.Crawling.ImportJobState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnName("correlation_id")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkCount")
                        .HasColumnName("chunk_count")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentState")
                        .HasColumnName("current_state")
                        .HasColumnType("text");

                    b.Property<int>("DocCount")
                        .HasColumnName("doc_count")
                        .HasColumnType("integer");

                    b.Property<Guid>("JobId")
                        .HasColumnName("job_id")
                        .HasColumnType("uuid");

                    b.Property<string>("ImporterType")
                        .IsRequired()
                        .HasColumnName("importer_type")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnName("source_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnName("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CorrelationId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("import_job_states");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnName("error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnName("finished_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceId")
                        .HasColumnName("source_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnName("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SourceId");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .HasColumnName("config")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnName("enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ImporterType")
                        .HasColumnName("importer_type")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastImportedAt")
                        .HasColumnName("last_imported_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnName("schedule")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("sources");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Chunk", b =>
                {
                    b.HasOne("Gravion.Noesis.Core.Entities.Doc", "Doc")
                        .WithMany("Chunks")
                        .HasForeignKey("DocId");

                    b.Navigation("Doc");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Doc", b =>
                {
                    b.HasOne("Gravion.Noesis.Core.Entities.Source", "Source")
                        .WithMany("Docs")
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Embedding", b =>
                {
                    b.HasOne("Gravion.Noesis.Core.Entities.Chunk", "Chunk")
                        .WithMany("Embeddings")
                        .HasForeignKey("ChunkId");

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Job", b =>
                {
                    b.HasOne("Gravion.Noesis.Core.Entities.Source", "Source")
                        .WithMany("Jobs")
                        .HasForeignKey("SourceId")
                        .IsRequired(false);

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Chunk", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Doc", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Gravion.Noesis.Core.Entities.Source", b =>
                {
                    b.Navigation("Docs");
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
